environment: preprod
network: hoodi
cronJob:
  namespace: internal-preprod-hoodi
  enabled: true
  schedule: "0 7 * * *"  # Run daily at 7 AM UTC (after sidecar-rewards-refresher at 6 AM)
  image:
    tag: latest
  config: |
    debug: true

    environment: "preprod"
    network: "hoodi"
    rewards_coordinator_address: "0xfc67a24cdb9ee82f6111082274c62d8b2aae3abc"
    sidecar_rpc_url: "sidecar.internal-preprod-hoodi.svc.cluster.local:7100"
    sidecar_insecure_rpc: true

claimJob:
  enabled: false
verifyRootJob:
  enabled: false
rewardsDataJob:
  enabled: false
