environment: preprod
network: holesky
version: ""
cronJob:
  name: rewards-updater
  enabled: true
  schedule: "*/15 * * * *"    # Runs every 15 minutes looking for new roots to post
  image:
    repository: public.ecr.aws/z6g0f8n7/eigenlayer-rewards-updater
    tag: latest
    pullPolicy: Always
  config: |
    debug: true

    rpc_url: "https://ethereum-holesky-rpc.publicnode.com"
    proof_store_base_url: "https://eigenlabs-rewards-preprod-holesky.s3.amazonaws.com"

claimJob:
  name: rewards-claimer
  enabled: false
  schedule: "35 13 * * *"
  image:
    repository: public.ecr.aws/z6g0f8n7/eigenlayer-rewards-updater
    tag: latest
    pullPolicy: Always
  config: |
    debug: true

    rpc_url: "https://ethereum-holesky-rpc.publicnode.com"
    proof_store_base_url: "https://eigenlabs-rewards-preprod-holesky.s3.amazonaws.com"
    earner_address: ""
    tokens: []
    claim_timestamp: 'latest'
    submit_claim: true

verifyRootJob:
  name: rewards-validator
  enabled: true
  schedule: "*/15 * * * *"
  image:
    repository: public.ecr.aws/z6g0f8n7/eigenlayer-rewards-updater
    tag: latest
    pullPolicy: Always
  config: |
    debug: true

    rpc_url: "https://ethereum-holesky-rpc.publicnode.com"
    proof_store_base_url: "https://eigenlabs-rewards-preprod-holesky.s3.amazonaws.com"
rewardsDataJob:
  name: rewards-data
  enabled: true
  schedule: "0 6 * * *" # run daily at 6am UTC
  image:
    repository: fullstorydev/grpcurl
    tag: latest
